apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  template:
    metadata:
      name: customer
      labels:
        app: customer
    spec:
      serviceAccountName: gateway
      containers:
        - name: customer
          image: odg18/customer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
      restartPolicy: Always
  selector:
    matchLabels:
      app: customer