server:
  port: 8080

spring:
  datasource:
    username: 'amigoscode'
    url: jdbc:postgresql://postgres:5432/customer
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
    show-sql: 'true'
  cloud:
    discovery:
      locator:
        enabled: true
    kubernetes:
      loadbalancer:
        enabled: true
      enabled: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
  security:
    user:
      name: customer
      password: customer
  boot:
    admin:
      client:
        url: http://spring-boot-admin-server:9102
        username: admin
        password: admin
      instance:
        metadata:
          user:
            name: ${spring.security.user.name}
            password: ${spring.security.user.password}

eureka:
  client:
    enabled: false

management:
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"