# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']

  # Discover targets from Eureka and scrape metrics from them (Whitebox monitoring)
  - job_name: eureka-discovery
    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka
        refresh_interval: 30s
    metrics_path: '/actuator/prometheus'
#    relabel_configs:
#      - source_labels: [__meta_eureka_app_name]
#        target_label: application
#      - source_labels: [__meta_eureka_app_instance_metadata_metrics_path]
#        target_label: __metrics_path__
#      - source_labels: [__address__]
#        target_label: instance

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
#  - job_name: 'myapp_metrics'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['myapp:8080']