server:
  port: 8082
spring:
  datasource:
    username: 'amigoscode'
    url: jdbc:postgresql://postgres:5432/notification
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
    show-sql: 'true'
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
  cloud:
    kubernetes:
      enabled: false
  security:
    user:
      name: notification
      password: notification
  boot:
    admin:
      client:
        url: http://spring-boot-admin-server:9102
        username: admin
        password: admin
      instance:
        metadata:
          user:
            name: ${spring.security.user.name}
            password: ${spring.security.user.password}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

management:
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"