server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #lowerCaseServiceId: true
          lower-case-service-id: true
          #url-expression: "'http://'+serviceId"
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/api/v1/customers/**
        - id: fraud
          uri: lb://fraud
          predicates:
            - Path=/api/v1/fraud-check/**

    kubernetes:
      reload:
        enabled: true
      loadbalancer:
        enabled: true
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

eureka:
  client:
    enabled: false



