server:
  port: 8083

spring:
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    kubernetes:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/api/v1/customers/**
        - id: fraud
          uri: lb://fraud
          predicates:
            - Path=/api/v1/fraud-check/**

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    enabled: false