apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      serviceAccountName: demo-role
      containers:
        - name: notification
          image: odg18/notification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 120
            timeoutSeconds: 30
            periodSeconds: 30
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 120
            timeoutSeconds: 30
            periodSeconds: 30
            failureThreshold: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification