server:
  port: 8081
spring:
  datasource:
    username: 'amigoscode'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411
  cloud:
    kubernetes:
      enabled: false
  security:
    user:
      name: fraud
      password: fraud
#  boot:
#    admin:
#      client:
#        url: http://localhost:9102
#        username: admin
#        password: admin
#      instance:
#        metadata:
#          user:
#            name: ${spring.security.user.name}
#            password: ${spring.security.user.password}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"