server:
  port: 9102

spring:
  cloud:
    kubernetes:
      enabled: true
  security:
    user:
      name: admin
      password: admin

  #configs to connect to self register the admin server as a client
  boot:
    admin:
      client:
        url: http://spring-boot-admin-server:9102
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        #configs to give secured server info
      instance:
        metadata:
          user:
            name: ${spring.security.user.name}
            password: ${spring.security.user.password}
      ui:
        public-url: http://api-gateway/admin-server/

management:
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    enabled: false