apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  labels:
    app: fraud
spec:
  replicas: 1
  template:
    metadata:
      name: fraud
      labels:
        app: fraud
    spec:
      serviceAccountName: demo-role
      containers:
        - name: fraud
          image: odg18/fraud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 120
            timeoutSeconds: 30
            periodSeconds: 30
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 120
            timeoutSeconds: 30
            periodSeconds: 30
            failureThreshold: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: fraud