server:
  port: 8080

spring:
  datasource:
    username: 'amigoscode'
    url: jdbc:postgresql://postgres:5432/customer
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
    show-sql: 'true'
  cloud:
    discovery:
      locator:
        enabled: true
    kubernetes:
      loadbalancer:
        enabled: true
      enabled: true

  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    enabled: false