server:
  port: 9101

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/olivier-deguise/microservices-demo
          searchPaths: config-server-repo/**
          default-label: master
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true