server:
  port: 9101

spring:
  application:
    name: config-server
  cloud:
    kubernetes:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/olivier-deguise/microservices-demo
          searchPaths: config-server-repo/**
          default-label: master
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"