server:
  port: 9101

spring:
  application:
    name: config-server
  cloud:
    kubernetes:
      enabled: false
    config:
      server:
        git:
          uri: https://github.com/olivier-deguise/microservices-demo
          searchPaths: config-server-repo/**
          default-label: master
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"